# Title and description of site
title         : 'eo11'
description   : 'eo11'
slogan        : 'It's all a state of mind, whether or not you find that place down there or heaven. In the meantime, eo11.'
'

# Build settings
url           : 'https://eo11.io/'
baseurl       : ''
markdown      : kramdown
highlighter   : rouge
permalink     : /:categories/:title/
encoding      : utf-8
destination   : _site
lang          : 'en'             # The language setting is used in /includes/header.html for html-settings


# Frontpage-Layout-Settings
posts_with_teaser_limit  : 1     # Define how many posts should be shown with headline, teaser, image, video
posts_list_limit         : 15    # Define how many posts should be shown in the list beneath the post(s)
excerpt_separator: <!--more-->   # Use <!--more--> in your posts to generate an excerpt and a teaser


# Available color schemes:
#
#  - simplicity
#  - gloom_contrast
#  - glowfish
#  - legacy
#  - yule

color_scheme: simplicity



#   Choose one of the following font combinations:
#
#   import is necessary to import the font from google
#   the settings for the fonts are used in /assets/css/simplicity.scss
font:
  import: 'Source+Code+Pro|Source+Sans+Pro:400,400italic,700,700italic'
#  import: 'Titillium+Web:400,400italic,700,700italic'
#  import: 'Roboto:400,400italic,700,700italic|Roboto+Mono'
#  import: 'Merriweather:400,400italic,700,700italic'
#  import: 'Arvo:400,400italic,700,700italic'
#  import: 'Gentium+Basic:400,400italic,700,700italic'
#  import: 'Fira+Sans:400,400italic,700,700italic|Fira+Mono'
  font-family-serif         : 'Georgia, "Times New Roman", serif;'
  font-family-sans-serif    : '"Source Sans Pro", "Neue Helvetica", Arial, serif;'
  base-font-family          : '"Source Sans Pro", "Neue Helvetica", Arial, serif;'
  font-family-monospace     : '"Source Code Pro", "Courier New", Monaco, monospace;'
  header-font-family        : '"Source Sans Pro", "Neue Helvetica", Arial, serif;'

#   Choose a modular scale.
#   What is a modular scale?
#   Read this › http://alistapart.com/article/more-meaningful-typography

modular_scale: modular_scale_1em
# modular_scale: modular_scale_ratio_1_125


# Default Settings

defaults:
  -
    scope:
      path: ''        # an empty string here means all files in the project
      type: 'pages'
    values:
      layout: page      # Set default layout to page
      show_meta: false  # Hide metadata for all pages
      comments: false
      author: 'Moritz »mo.« Sauer'     # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: page      # Set default layout to page
      show_meta: true   # Show metadata for all posts
      comments: false
      author: 'Moritz »mo.« Sauer'     # Default author for posts


# SEO: Verify Website to Webmaster Tools

# google_site_verification   : ''
# bing_webmastertools_id   : ''
# alexa_verify_id          : ''



#       ______            _
#      / ____/___ __   __(_)________  ____  _____
#     / /_  / __ `/ | / / / ___/ __ \/ __ \/ ___/
#    / __/ / /_/ /| |/ / / /__/ /_/ / / / (__  )
#   /_/    \__,_/ |___/_/\___/\____/_/ /_/____/   Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
#                                                 More information » https://mathiasbynens.be/notes/touch-icons

favicon-32x32:                          'favicon-32x32.png'
touch-icon-192x192:                     'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed:   'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed:   'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed:   'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed:   'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed:   'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed:     'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed:     'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed:           'apple-touch-icon-precomposed.png'
msapplication_tileimage:                'msapplication_tileimage.png'               # Size 144x144
msapplication_tilecolor:                '#fabb00'


#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#

sass:
    sass_dir: _sass
    style: :compressed


#        ____  _
#       / __ \(_)________ ___  _______
#      / / / / / ___/ __ `/ / / / ___/
#     / /_/ / (__  ) /_/ / /_/ (__  )
#    /_____/_/____/\__, /\__,_/____/
#                    /_/
#
# used in _includes/comments

# disqus_shortname:


#       ___                __      __  _
#      /   |  ____  ____ _/ /_  __/ /_(_)_________
#     / /| | / __ \/ __ `/ / / / / __/ / ___/ ___/
#    / ___ |/ / / / /_/ / / /_/ / /_/ / /__(__  )
#   /_/  |_/_/ /_/\__,_/_/\__, /\__/_/\___/____/      https://www.google.com/analytics/
#                        /____/
#
# used in _includes/_4_footer_scripts

# google_analytics_tracking_id:


socialmedia:
    # youtube: PhlowMedia
    # github: phlow
    # twitter: phlow
    # facebook: phlow.media
    # soundcloud: phlow
    # tumblr: motizen
    # instagram: phlowmedia
    # rss: # Full URL needed

plugins:
    - jekyll-gist
    - jekyll-sitemap
    - jekyll-paginate

# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - README.md
    - INSTALL.md
    - vendor


compress_html:
  clippings : all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]
